using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace VoxLink.Api.Pdf;

public static class AgreementPdfGenerator
{
    public static byte[] Generate(
        string companyName,
        string termsVersion,
        string agreedByName,
        string agreedByEmail,
        DateTimeOffset agreedAt,
        string? ipAddress)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("VoxLink — Pay-As-You-Go Services Agreement").FontSize(18).Bold();

                page.Content().Column(col =>
                {
                    col.Spacing(12);

                    col.Item().Text($"Terms version: {termsVersion}").FontSize(9).FontColor(Colors.Grey.Darken1);
                    col.Item().Text($"Client: {companyName}");

                    col.Item().PaddingTop(10).Text(
                        "This agreement confirms that the above client engages VoxLink on a pay-as-you-go " +
                        "basis for calling platform services. Charges are billed monthly based on the " +
                        "client's selected plan and actual call usage during each billing period. The " +
                        "client agrees to settle each invoice within the stated due date by bank transfer " +
                        "to VoxLink's nominated account, and to upload proof of payment for each invoice " +
                        "via the VoxLink platform.");

                    col.Item().PaddingTop(10).Text("Electronic signature").Bold();
                    col.Item().Text($"Agreed by: {agreedByName} ({agreedByEmail})");
                    col.Item().Text($"Agreed at: {agreedAt:yyyy-MM-dd HH:mm} UTC");
                    col.Item().Text($"IP address: {ipAddress ?? "unknown"}");
                    col.Item().Text(
                        "By checking \"I agree\" and submitting this form, the person named above confirmed " +
                        "acceptance of these terms on behalf of the client company.");
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by VoxLink — ").FontSize(8).FontColor(Colors.Grey.Darken1);
                    t.Span(DateTimeOffset.UtcNow.ToString("yyyy-MM-dd HH:mm") + " UTC").FontSize(8).FontColor(Colors.Grey.Darken1);
                });
            });
        }).GeneratePdf();
    }
}
